let data = [
  {
      id: 0,
      name: "런스타 하이크 블랙",
      price: 109000,
      gender: "남녀공용",
      type: "best seller",
      content: "척테일러 올스타의 과감한 미래지향적인 재해석",
      rate: 4.7,
      size: [225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300],
  },
  {
      id: 1,
      name: "런스타 하이크 시즈널 컬러 아이언 그레이  ",
      price: 109000,
      gender: "여성용",
      type: "new arrival",
      content: "오감을 달래는 새로운 소프트 컬러로 돌아온 베스트셀러 런 스타 하이크",
      frontImg: "img/bestproduct1.jpg",
      backImg: "img/bestproduct1-1.jpg",
  },
  {
      id: 2,
      name: "런스타 하이크 시즈널 컬러 슬레이트 라일락",
      price: 109000,
      gender: "여성용",
      type: "new arrival",
      content: "오감을 달래는 새로운 소프트 컬러로 돌아온 베스트셀러 런 스타 하이크",
      frontImg: "img/bestproduct2.jpg",
      backImg: "img/bestproduct2-1.jpg",
  },
  {
      id: 3,
      name: "런스타 하이크 시즈널 컬러 새들",
      price: 109000,
      gender: "여성용",
      type: "new arrival",
      content: "오감을 달래는 새로운 소프트 컬러로 돌아온 베스트셀러 런 스타 하이크",
      frontImg: "img/bestproduct3.jpg",
      backImg: "img/bestproduct3-1.jpg",
  },
]
export default data;